### ISSUE TITLE
Unable to select an image in "picture" tab

### ISSUE THREAD

**Issue by Utharlepreux** [EvanesceExotica/Journal-To-Canvas-Slideshow#42]
Hi, thanks for your great work. I have an issue regarding the possibility to display an image that is on the "picture" tab on a actor sheet or journal page. 
To be more specific : when you select an actor (left click) you have the possibility to display the character sheet. Then you can display with JTCS the image on the up left corner. But if you "richt click" the actor's name and select "display image" or "display token image" said image is not displayable with JTCS. 
Same for journal image : if you select an image within the "text" tab of the journal page no problem. But if said image is on the image tab of displayed journal page then you cannot select said image with JTCS. The controls are missing despite the JTCS general controls on the right low corner and the image being color surrounded rightly.
You will see pictures below that explain the problem.
System is Warhammer Fantasy

![Capture d’écran 2022-10-22 à 10 35 23](https://user-images.githubusercontent.com/40202908/197330208-8ee09a15-55da-4bc0-b7bf-9ef4e1526ed0.png)
![Capture d’écran 2022-10-22 à 10 35 34](https://user-images.githubusercontent.com/40202908/197330207-480fc1a8-9c46-488c-9fd7-824a1853ce7e.png)
![Capture d’écran 2022-10-22 à 10 36 00](https://user-images.githubusercontent.com/40202908/197330205-07adfe29-9bd8-4a85-89bb-360cae201149.png)
![Capture d’écran 2022-10-22 à 10 36 52](https://user-images.githubusercontent.com/40202908/197330204-ae484fe3-062b-4e3e-abcb-23020090e7ac.png)
![Capture d’écran 2022-10-22 à 10 43 34](https://user-images.githubusercontent.com/40202908/197330203-b4abc718-e9a2-472a-a94a-571142139554.png)

**Comment by Evannessa** [comment]
Sorry for the issues you're having, and thanks so much for your patience ^ ^ I'll try to get this fixed as soon as I can

**Comment by Utharlepreux** [comment]
Thanks a lot for your answer !

**Comment by propri** [comment]
I've got the same problem with the dnd5e system:

Working in text tab:

![image](https://user-images.githubusercontent.com/38747561/208268862-530f6190-1428-4ee0-9642-63c240b3bb9a.png)

Not working in image tab:

![image](https://user-images.githubusercontent.com/38747561/208268881-f5f08244-092c-4582-84ec-04db13903f41.png)

The console shows the following error when switching the journal from the text tab to the image tab:
```
SheetImageDataController.js:127 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'replace')
[Detected 1 package: journal-to-canvas-slideshow]
    at SheetImageDataController.convertImageSourceToID (SheetImageDataController.js:127:21)
    at SheetImageApp.injectImageControls (SheetImageApp.js:126:58)
```

![image](https://user-images.githubusercontent.com/38747561/208268957-770ef6ee-d74b-416a-9560-325a58f5f454.png)


Edit: Using foundry 9.269 and JTCS 0.2.4
